const env = {
  ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET!,
  REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET!,
  JWT_ALGORITHM: process.env.JWT_ALGORITHM || "HS256",

  ACCESS_TOKEN_EXPIRES_IN: process.env.ACCESS_TOKEN_EXPIRES_IN || "1h",
  REFRESH_TOKEN_EXPIRES_IN: process.env.REFRESH_TOKEN_EXPIRES_IN || "7d",

  ACCESS_COOKIE_NAME: process.env.ACCESS_COOKIE_NAME || "freeai_access_token",
  REFRESH_COOKIE_NAME: process.env.REFRESH_COOKIE_NAME || "freeai_refresh_token",

  ACCESS_COOKIE_MAX_AGE: parseInt(process.env.ACCESS_COOKIE_MAX_AGE || "3600", 10),
  REFRESH_COOKIE_MAX_AGE: parseInt(process.env.REFRESH_COOKIE_MAX_AGE || "604800", 10),

  COOKIE_SECURE: process.env.COOKIE_SECURE === "true",
  COOKIE_HTTP_ONLY: process.env.COOKIE_HTTP_ONLY !== "false",
  COOKIE_SAME_SITE: (process.env.COOKIE_SAME_SITE || "lax") as "lax" | "strict" | "none",

  ADMIN_ACCESS_TOKEN_SECRET: process.env.ADMIN_ACCESS_TOKEN_SECRET!,
  ADMIN_REFRESH_TOKEN_SECRET: process.env.ADMIN_REFRESH_TOKEN_SECRET!,
  ADMIN_ACCESS_TOKEN_EXPIRES_IN: process.env.ADMIN_ACCESS_TOKEN_EXPIRES_IN || "1h",
  ADMIN_REFRESH_TOKEN_EXPIRES_IN: process.env.ADMIN_REFRESH_TOKEN_EXPIRES_IN || "7d",
  ADMIN_ACCESS_COOKIE_NAME: process.env.ADMIN_ACCESS_COOKIE_NAME || "nexachat_admin_access",
  ADMIN_REFRESH_COOKIE_NAME: process.env.ADMIN_REFRESH_COOKIE_NAME || "nexachat_admin_refresh",
  ADMIN_ACCESS_COOKIE_MAX_AGE: parseInt(process.env.ADMIN_ACCESS_COOKIE_MAX_AGE || "3600", 10),
  ADMIN_REFRESH_COOKIE_MAX_AGE: parseInt(process.env.ADMIN_REFRESH_COOKIE_MAX_AGE || "604800", 10),
  ADMIN_EMAIL: process.env.ADMIN_EMAIL || "admin@nexachat.com",
  ADMIN_PASSWORD: process.env.ADMIN_PASSWORD || "Admin@123",

  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY!,
  STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET!,
  STRIPE_PUBLISHABLE_KEY: process.env.STRIPE_PUBLISHABLE_KEY!,
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY!,
  SITE_URL: process.env.SITE_URL || "http://localhost:3000",

  MIMO_API_KEY: process.env.MIMO_API_KEY!,
  DATABASE_URL: process.env.DATABASE_URL!,
}

export default env
